---
  - hosts: all
    tasks:
    - name: Create WordPress database
      mysql_db: name={{ wp_db_name }} login_host={{ wp_db_url }} login_user={{ rds_master_user }} login_password={{ rds_master_password }} state=present

    - name: Create WordPress database user
      mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} login_user={{ rds_master_user }} login_password={{ rds_master_password }} priv={{ wp_db_name }}.*:ALL host='%' login_host={{ wp_db_url }} state=present
